# Generated by Django 4.2.2 on 2024-01-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='slug',
        ),
        migrations.AlterField(
            model_name='sections',
            name='section',
            field=models.CharField(max_length=15),
        ),
    ]
