# Generated by Django 4.2.2 on 2024-03-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='application',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
