# Generated by Django 4.2.2 on 2024-03-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_remove_categories_description_products_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
