# Generated by Django 4.2.2 on 2024-03-10 11:42

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_of_organization',
            field=models.CharField(max_length=25, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='tin',
            field=models.CharField(max_length=12, validators=[orders.validators.validate_len_of_tin], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Ваше имя'),
        ),
    ]
